name: MasterRelease
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    # https://github.com/marketplace/actions/github-tag-bump
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO_OWNER: jtviegas
        WITH_V: true
        source: ${GITHUB_WORKSPACE}/modules
